

// -------------------------------------------------------------
// <copyright company="Pipeline Group, Inc." file="EFRepository.cs">
// COPYRIGHT NOTICE

// SOFTWARE CONTAINING TRADE SECRETS

// Copyright 2012 Pipeline Group, Inc.  (PIPELINE GROUP, INC ). All rights reserved.

// This software and documentation constitute an unpublished work and contain valuable
// trade secrets and proprietary information belonging to the PIPELINE GROUP, INC .
// None of the foregoing material may be copied, duplicated or disclosed without the 
// express written permission of the PIPELINE GROUP, INC .

// PIPELINE GROUP, INC  EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES CONCERNING THIS 
// SOFTWARE AND DOCUMENTATION, INCLUDING ANY WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
// FOR ANY PARTICULAR PURPOSE, AND WARRANTIES OF PERFORMANCE, AND ANY WARRANTY THAT MIGHT 
// OTHERWISE ARISE FROM COURSE OF DEALING OR USAGE OF TRADE.
// NO WARRANTY IS EITHER EXPRESS OR IMPLIED WITH RESPECT TO THE USE OF THE SOFTWARE OR 
// DOCUMENTATION. 

// Under no circumstances shall PIPELINE GROUP, INC  be liable for incidental, special, indirect, direct 
// or consequential damages or loss of profits, interruption of business, or related expenses 
// which may arise from use of software or documentation, including but not limited to those 
// resulting from defects in software and/or documentation, or loss or inaccuracy of data 
// of any kind.

// </copyright>
// <author>$Author: pmontgomery $</author>
// <remarks>
//   $HeadURL: https://pipesvn.pipelinenetwork.com/svn/STP/Product/branches/Release/81/WebApp/Plugin_WorkAssignment/Model/EFRepository.cs $
//   $LastChangedRevision: 8133 $ 
//   $LastChangedDate: 2013-07-26 09:56:05 -0700 (Fri, 26 Jul 2013) $ 
//   $LastChangedBy: pmontgomery $ 
// </remarks>  
// <summary>  
//   Repository to create, read, update, and delete entities from Oracle via Entity Framework  
// </summary> 
// ------------------------------------------------------------- 

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Objects;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using Plugin_WorkAssignment.ModelAPI;

namespace Plugin_WorkAssignment.Model
{
	/// <summary>
	/// Database implementation of a repository
	/// </summary>
	public class EFRepository<T> : IRepository<T> where T : class
	{
		/// <summary>
		/// Repository Unit Of Work Property
		/// </summary>
		public IUnitOfWork UnitOfWork
        { 
            get
            {
                return this._unitOfWork;
            }

            set
            {
                this._unitOfWork = value;
            
                // Reset object set to retrieve from current context
                this._objectSet = null;
            }
        }

		/// <summary>
		/// Repository Unit Of Work
		/// </summary>
        private IUnitOfWork _unitOfWork = null;

		/// <summary>
		/// Object set of data property
		/// </summary>
        public IObjectSet<T> ObjectSet
        {
            get
            {
                if (this._objectSet == null)
                {
                    this._objectSet = UnitOfWork.Context.CreateObjectSet<T>();
                }
                return this._objectSet;
            }
        }

		/// <summary>
		/// Object set of data
		/// </summary>
        private IObjectSet<T> _objectSet = null;

		/// <summary>
		/// Retrieve all from the repository
		/// </summary>
		/// <returns>>A query</returns>
		public virtual IQueryable<T> All()
		{
			return ObjectSet.AsQueryable();
		}

		/// <summary>
		/// Where clause for a query
		/// </summary>
		/// <param name="expression">Parameters for a where clause</param>
		/// <returns>A query</returns>
		public IQueryable<T> Where(Expression<Func<T, bool>> expression)
		{
			return ObjectSet.Where(expression);
		}

		/// <summary>
		/// Add object to repository
		/// </summary>
		/// <param name="entity">Object to add to repository</param>
		public void Add(T entity)
		{
			ObjectSet.AddObject(entity);
		}

		/// <summary>
		/// Delete object from repository
		/// </summary>
		/// <param name="entity">Object to delete from repository</param>
		public void Delete(T entity)
		{
			ObjectSet.DeleteObject(entity);
		}

        /// <summary>
        /// Updates a respository object
        /// </summary>
        /// <param name="entity"></param>
        public void Update(T entity)
        {
            if (this._objectSet is ObjectSet<T>)
            {
                ObjectSet<T> objectSet = ObjectSet as ObjectSet<T>;
                objectSet.ApplyCurrentValues(entity);
            }
        }
	}
}

