// -------------------------------------------------------------
// <copyright company="Pipeline Group, Inc." file="RepositoryIQueryableExtensions.cs">
// COPYRIGHT NOTICE

// SOFTWARE CONTAINING TRADE SECRETS

// Copyright 2012 Pipeline Group, Inc.  (PIPELINE GROUP, INC ). All rights reserved.

// This software and documentation constitute an unpublished work and contain valuable
// trade secrets and proprietary information belonging to the PIPELINE GROUP, INC .
// None of the foregoing material may be copied, duplicated or disclosed without the 
// express written permission of the PIPELINE GROUP, INC .

// PIPELINE GROUP, INC  EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES CONCERNING THIS 
// SOFTWARE AND DOCUMENTATION, INCLUDING ANY WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
// FOR ANY PARTICULAR PURPOSE, AND WARRANTIES OF PERFORMANCE, AND ANY WARRANTY THAT MIGHT 
// OTHERWISE ARISE FROM COURSE OF DEALING OR USAGE OF TRADE.
// NO WARRANTY IS EITHER EXPRESS OR IMPLIED WITH RESPECT TO THE USE OF THE SOFTWARE OR 
// DOCUMENTATION. 

// Under no circumstances shall PIPELINE GROUP, INC  be liable for incidental, special, indirect, direct 
// or consequential damages or loss of profits, interruption of business, or related expenses 
// which may arise from use of software or documentation, including but not limited to those 
// resulting from defects in software and/or documentation, or loss or inaccuracy of data 
// of any kind.

// </copyright>
// <author>$Author: pmontgomery $</author>
// <remarks>
//   $HeadURL: https://pipesvn.pipelinenetwork.com/svn/STP/Product/branches/Release/81/WebApp/Plugin_WorkAssignment/Model/RepositoryIQueryableExtensions.cs $
//   $LastChangedRevision: 8133 $ 
//   $LastChangedDate: 2013-07-26 09:56:05 -0700 (Fri, 26 Jul 2013) $ 
//   $LastChangedBy: pmontgomery $ 
// </remarks>  
// <summary>  
//   Extension methods for repository classes  
// </summary> 
// ------------------------------------------------------------- 

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Objects;
using System.Linq;
using System;

namespace Plugin_WorkAssignment.Model
{
	/// <summary>
	/// Extension methods for repositories
	/// </summary>
	public static class RepositoryIQueryableExtensions
	{
		/// <summary>
		/// Specifies objects to include in query
		/// </summary>
		/// <param name="source">Queryable object to add method to</param>
		/// <param name="path">Path of object to include</param>
		/// <returns>A query</returns>
		public static IQueryable<T> Include<T>
			(this IQueryable<T> source, string path)
		{
			var objectQuery = source as ObjectQuery<T>;
			if (objectQuery != null)
			{
				return objectQuery.Include(path);
			}
			return source;
		}

        /// <summary>
        /// Translates into SQL "LIKE" statement.  Allows code to compile even though method defined in .edmx
        /// </summary>
        /// <param name="searchingIn">Field to perform "LIKE" on</param>
        /// <param name="lookingFor">Search value</param>
        /// <returns>Result from SQL "LIKE"</returns>
        [System.Data.Objects.DataClasses.EdmFunction("Model", "String_Like")]
        public static Boolean String_Like(this String searchingIn, String lookingFor)
        {
            throw new Exception("Not implemented");
        }
	}
}