// -------------------------------------------------------------
// <copyright company="Pipeline Group, Inc." file="VW_TECHNICIAN_ASSIGN_AVAILRepository.cs">
// COPYRIGHT NOTICE

// SOFTWARE CONTAINING TRADE SECRETS

// Copyright 2012 Pipeline Group, Inc.  (PIPELINE GROUP, INC ). All rights reserved.

// This software and documentation constitute an unpublished work and contain valuable
// trade secrets and proprietary information belonging to the PIPELINE GROUP, INC .
// None of the foregoing material may be copied, duplicated or disclosed without the 
// express written permission of the PIPELINE GROUP, INC .

// PIPELINE GROUP, INC  EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES CONCERNING THIS 
// SOFTWARE AND DOCUMENTATION, INCLUDING ANY WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
// FOR ANY PARTICULAR PURPOSE, AND WARRANTIES OF PERFORMANCE, AND ANY WARRANTY THAT MIGHT 
// OTHERWISE ARISE FROM COURSE OF DEALING OR USAGE OF TRADE.
// NO WARRANTY IS EITHER EXPRESS OR IMPLIED WITH RESPECT TO THE USE OF THE SOFTWARE OR 
// DOCUMENTATION. 

// Under no circumstances shall PIPELINE GROUP, INC  be liable for incidental, special, indirect, direct 
// or consequential damages or loss of profits, interruption of business, or related expenses 
// which may arise from use of software or documentation, including but not limited to those 
// resulting from defects in software and/or documentation, or loss or inaccuracy of data 
// of any kind.

// </copyright>
// <author>$Author: pmontgomery $</author>
// <remarks>
//   $HeadURL: https://pipesvn.pipelinenetwork.com/svn/STP/Product/branches/Release/81/WebApp/Plugin_WorkAssignment/Model/VW_TECHNICIAN_ASSIGN_AVAILRepository.cs $
//   $LastChangedRevision: 9794 $ 
//   $LastChangedDate: 2013-12-16 14:13:21 -0800 (Mon, 16 Dec 2013) $ 
//   $LastChangedBy: pmontgomery $ 
// </remarks>  
// <summary>  
//   Provides access to available hours and assigned hours for all technicians for each day from an Oracle database  
// </summary> 
// ------------------------------------------------------------- 

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Plugin_WorkAssignment.ModelAPI;
using Microsoft.Practices.Unity;
using Logging;
using Utilities.ErrorHandling;
using Utilities;
using System.Data.Objects;
	
namespace Plugin_WorkAssignment.Model
{   
	/// <summary>
	/// VW_TECHNICIAN_ASSIGN_AVAIL Repository
	/// </summary>
	public partial class VW_TECHNICIAN_ASSIGN_AVAILRepository : EFRepository<VW_TECHNICIAN_ASSIGN_AVAIL>, IVW_TECHNICIAN_ASSIGN_AVAILRepository
    {
        #region Public methods
        /// <summary>
        /// Sets logger
        /// </summary>
        /// <param name="logger">Logger for logging</param>
        [InjectionMethod]
        public void Initialize(ILogger<VW_TECHNICIAN_ASSIGN_AVAILRepository> logger)
        {
            _logger = logger;

            _logger.Debug("VW_TECHNICIAN_ASSIGN_AVAILRepository::Initialize method.");
        }

        /// <summary>
        /// Get all available hours and assigned hours for all technicians in a shop for the specified work
        /// </summary>
        /// <param name="startWorkWeek">Start of work week to filter by</param>
        /// <param name="startWorkWeek">End of work week to filter by</param>
        /// <param name="shop">Shop technician's belong to</param>
        /// <returns>All available hours and assigned hours for all technicians in a shop for the specified work week</returns>
        /// <exception cref="DataBaseException">Database error getting data</exception>
        public List<VW_TECHNICIAN_ASSIGN_AVAIL> GetAll(DateTime? startWorkWeek, DateTime? finishWorkWeek, string shop)
        {
            _logger.Debug("VW_TECHNICIAN_ASSIGN_AVAILRepository::GetAll method.");

            if (_logger.IsTraceEnabled == true)
            {
                _logger.Trace(
                    "Call parameters {startWorkWeek = {0}, finishWorkWeek = {1}, shop = {2}}",
                    startWorkWeek,
                    finishWorkWeek,
                    shop);
            }

            List<VW_TECHNICIAN_ASSIGN_AVAIL> result = null;

            if ((string.IsNullOrEmpty(shop) == true) || (startWorkWeek.HasValue == false) || (finishWorkWeek.HasValue == false))
            {
                // The above should never occur since there always needs to be a shop and date
                return null;
            }

            try
            {
                var query = this.Where(techUtil => techUtil.WORK_DATE >= startWorkWeek.Value &&
                    techUtil.WORK_DATE < finishWorkWeek &&
                    techUtil.SHOP == shop);

                if (_logger.IsTraceEnabled == true)
                {
                    // Log SQL
                    string message = ((ObjectQuery)query).ToTraceString();
                    _logger.Trace("SQL Statement: " + message);
                }

                result = query.ToList();
            }
            catch (Exception ex)
            {
                throw new DataBaseException(ex.Message, ex);
            }

            if (_logger.IsTraceEnabled == true)
            {
                _logger.Trace("Output of assigned and availabe hours for technicians for a given shop during a given week = {0}",
                    ObjectSerializingHelper.Serialize(result));
            }

            return result;
        }
        #endregion

        #region Private static variables
        /// <summary>
        /// Logger for logging
        /// </summary>
        private static ILogger<VW_TECHNICIAN_ASSIGN_AVAILRepository> _logger = null;
        #endregion
	}
}