--$Id: DATASOURCE_CUSTOM.sql 11599 2014-06-16 20:10:04Z ogarcia $
SET SQLBLANKLINES ON;
SET DEFINE OFF;
DECLARE
    cte_now DATASOURCE.CREATED_DATE%TYPE := SYSDATE;
    cte_author DATASOURCE.CREATED_BY%TYPE := 'SEED';
    cte_scanchanges DATASOURCE.LISTEN_FOR_CHANGE_IND%TYPE := 'Y';
    guid     DATASOURCE.ID%TYPE;
BEGIN
  MERGE INTO DATASOURCE o
  USING ( SELECT
    SYS_GUID() ID
    ,'Area' NAME
    ,cte_scanchanges LISTEN_FOR_CHANGE_IND
    ,'select VALUE, KEYNAME from LOOKUP_ITEM where LOOKUP_NAME = ''Area''' SQL_STMT
    ,'OracleProviders.Extensions.DataCaching.Readers.LookupItemReader, OracleProviders.Extensions' ADAPTOR_CLASS
    ,1 DISPLAY_VALUE
    ,cte_author CREATED_BY --cte_author CREATED_BY
    ,cte_now CREATED_DATE-- cte_now CREATED_DATE
    ,null  LAST_MODIFIED_BY --cte_author LAST_MODIFIED_BY
    ,null LAST_MODIFIED_DATE-- cte_now LAST_MODIFIED_DATE
    from dual
  ) n
  ON (o.NAME = n.NAME)
 WHEN NOT MATCHED THEN
     INSERT VALUES (n.ID, n.NAME, n.LISTEN_FOR_CHANGE_IND, n.SQL_STMT, n.ADAPTOR_CLASS, n.DISPLAY_VALUE, n.CREATED_BY, n.CREATED_DATE, n.LAST_MODIFIED_BY, n.LAST_MODIFIED_DATE)
 WHEN MATCHED THEN
     UPDATE SET o.LAST_MODIFIED_BY = n.CREATED_BY, o.LAST_MODIFIED_DATE = n.CREATED_DATE;
COMMIT;
END;
/