// -------------------------------------------------------------
// <copyright company="Pipeline Group, Inc." file="Filename.cs">
// COPYRIGHT NOTICE

// SOFTWARE CONTAINING TRADE SECRETS

// Copyright 2012 Pipeline Group, Inc.  (PIPELINE GROUP, INC ). All rights reserved.

// This software and documentation constitute an unpublished work and contain valuable
// trade secrets and proprietary information belonging to the PIPELINE GROUP, INC .
// None of the foregoing material may be copied, duplicated or disclosed without the 
// express written permission of the PIPELINE GROUP, INC .

// PIPELINE GROUP, INC  EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES CONCERNING THIS 
// SOFTWARE AND DOCUMENTATION, INCLUDING ANY WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
// FOR ANY PARTICULAR PURPOSE, AND WARRANTIES OF PERFORMANCE, AND ANY WARRANTY THAT MIGHT 
// OTHERWISE ARISE FROM COURSE OF DEALING OR USAGE OF TRADE.
// NO WARRANTY IS EITHER EXPRESS OR IMPLIED WITH RESPECT TO THE USE OF THE SOFTWARE OR 
// DOCUMENTATION. 

// Under no circumstances shall PIPELINE GROUP, INC  be liable for incidental, special, indirect, direct 
// or consequential damages or loss of profits, interruption of business, or related expenses 
// which may arise from use of software or documentation, including but not limited to those 
// resulting from defects in software and/or documentation, or loss or inaccuracy of data 
// of any kind.

// </copyright>
// <author>$Author$</author>
// <remarks>
//   $HeadURL$
//   $LastChangedRevision$ 
//   $LastChangedDate$ 
//   $LastChangedBy$ 
// </remarks>  
// <summary>  
//     
// </summary> 
// ------------------------------------------------------------- 

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.Text;

namespace Plugin_WorkAssignment.ModelAPI
{
    [DataContract]
    public partial class ACTIVITY
    {
        #region Primitive Properties
    
    	/// <summary>
    	/// Retrieve ID Property
    	/// </summary>
        [DataMember]
        public virtual decimal ID
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve SNAPSHOT_ID Property
    	/// </summary>
        [DataMember]
        public virtual decimal SNAPSHOT_ID
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve PROJECT_ID Property
    	/// </summary>
        [DataMember]
        public virtual string PROJECT_ID
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve ACT_NUM Property
    	/// </summary>
        [DataMember]
        public virtual string ACT_NUM
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve EXT_ID Property
    	/// </summary>
        [DataMember]
        public virtual string EXT_ID
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve EXT_TYPE Property
    	/// </summary>
        [DataMember]
        public virtual string EXT_TYPE
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve PROJECT_NAME Property
    	/// </summary>
        [DataMember]
        public virtual string PROJECT_NAME
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve DESCRIPTION Property
    	/// </summary>
        [DataMember]
        public virtual string DESCRIPTION
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve WBS Property
    	/// </summary>
        [DataMember]
        public virtual string WBS
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve PCT_COMP Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> PCT_COMP
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve ACTUAL_DURATION Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> ACTUAL_DURATION
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve REMAIN_DURATION Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> REMAIN_DURATION
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve ORIG_DURATION Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> ORIG_DURATION
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve ORIG_UNITS Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> ORIG_UNITS
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve REMAIN_UNITS Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> REMAIN_UNITS
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve PLANNED_START Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> PLANNED_START
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve PLANNED_FINISH Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> PLANNED_FINISH
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve START_DATE Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> START_DATE
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve FINISH_DATE Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> FINISH_DATE
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve ACTUAL_START Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> ACTUAL_START
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve ACTUAL_FINISH Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> ACTUAL_FINISH
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve REMAIN_EARLY_START Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> REMAIN_EARLY_START
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve REMAIN_EARLY_FINISH Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> REMAIN_EARLY_FINISH
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve RESUME_DATE Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> RESUME_DATE
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve SUSPEND_DATE Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> SUSPEND_DATE
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve SOURCE_TYPE Property
    	/// </summary>
        [DataMember]
        public virtual string SOURCE_TYPE
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve DEVIATION_CODE Property
    	/// </summary>
        [DataMember]
        public virtual string DEVIATION_CODE
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve DEVIATION_COMMENTS Property
    	/// </summary>
        [DataMember]
        public virtual string DEVIATION_COMMENTS
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve STATUS_CODE Property
    	/// </summary>
        [DataMember]
        public virtual string STATUS_CODE
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve PRED_STATUS_CODE Property
    	/// </summary>
        [DataMember]
        public virtual string PRED_STATUS_CODE
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve TOTAL_FLOAT Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> TOTAL_FLOAT
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve FREE_FLOAT Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> FREE_FLOAT
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CURRENT_FLOAT Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CURRENT_FLOAT
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CALENDAR Property
    	/// </summary>
        [DataMember]
        public virtual string CALENDAR
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve DATA_FOUND_IND Property
    	/// </summary>
        [DataMember]
        public virtual string DATA_FOUND_IND
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_1 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_1
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_2 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_2
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_3 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_3
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_4 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_4
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_5 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_5
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_6 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_6
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_7 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_7
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_8 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_8
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_9 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_9
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_10 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_10
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_11 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_11
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_12 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_12
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_13 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_13
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_14 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_14
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_15 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_15
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_16 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_16
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_17 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_17
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_18 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_18
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_19 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_19
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_20 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_20
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_21 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_21
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_22 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_22
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_23 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_23
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_24 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_24
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_25 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_25
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_26 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_26
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_27 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_27
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_28 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_28
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_29 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_29
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_30 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_30
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_31 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_31
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_32 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_32
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_33 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_33
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_34 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_34
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_35 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_35
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_36 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_36
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_37 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_37
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_38 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_38
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_39 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_39
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_40 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_40
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_41 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_41
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_42 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_42
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_43 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_43
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_44 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_44
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_45 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_45
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_46 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_46
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_47 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_47
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_48 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_48
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_49 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_49
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_STRING_50 Property
    	/// </summary>
        [DataMember]
        public virtual string CUSTOM_ATTR_STRING_50
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_DATE_1 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> CUSTOM_ATTR_DATE_1
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_DATE_2 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> CUSTOM_ATTR_DATE_2
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_DATE_3 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> CUSTOM_ATTR_DATE_3
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_DATE_4 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> CUSTOM_ATTR_DATE_4
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_DATE_5 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> CUSTOM_ATTR_DATE_5
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_DATE_6 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> CUSTOM_ATTR_DATE_6
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_DATE_7 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> CUSTOM_ATTR_DATE_7
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_DATE_8 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> CUSTOM_ATTR_DATE_8
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_DATE_9 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> CUSTOM_ATTR_DATE_9
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_DATE_10 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> CUSTOM_ATTR_DATE_10
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_INT_1 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_INT_1
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_INT_2 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_INT_2
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_INT_3 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_INT_3
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_INT_4 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_INT_4
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_INT_5 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_INT_5
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_INT_6 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_INT_6
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_INT_7 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_INT_7
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_INT_8 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_INT_8
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_INT_9 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_INT_9
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_INT_10 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_INT_10
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_NUM_1 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_NUM_1
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_NUM_2 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_NUM_2
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_NUM_3 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_NUM_3
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_NUM_4 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_NUM_4
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_NUM_5 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_NUM_5
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_NUM_6 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_NUM_6
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_NUM_7 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_NUM_7
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_NUM_8 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_NUM_8
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_NUM_9 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_NUM_9
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_NUM_10 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> CUSTOM_ATTR_NUM_10
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_BOOL_1 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<bool> CUSTOM_ATTR_BOOL_1
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_BOOL_2 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<bool> CUSTOM_ATTR_BOOL_2
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_BOOL_3 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<bool> CUSTOM_ATTR_BOOL_3
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_BOOL_4 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<bool> CUSTOM_ATTR_BOOL_4
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_BOOL_5 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<bool> CUSTOM_ATTR_BOOL_5
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_BOOL_6 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<bool> CUSTOM_ATTR_BOOL_6
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_BOOL_7 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<bool> CUSTOM_ATTR_BOOL_7
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_BOOL_8 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<bool> CUSTOM_ATTR_BOOL_8
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_BOOL_9 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<bool> CUSTOM_ATTR_BOOL_9
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve CUSTOM_ATTR_BOOL_10 Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<bool> CUSTOM_ATTR_BOOL_10
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve LAST_MODIFIED_DATE Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> LAST_MODIFIED_DATE
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve LAST_MODIFIED_BY Property
    	/// </summary>
        [DataMember]
        public virtual string LAST_MODIFIED_BY
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve DELETED_IND Property
    	/// </summary>
        [DataMember]
        public virtual string DELETED_IND
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve PENDING_TX_IND Property
    	/// </summary>
        [DataMember]
        public virtual string PENDING_TX_IND
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve EXT_REMAIN_DURATION Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> EXT_REMAIN_DURATION
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve DATA_DATE Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<System.DateTime> DATA_DATE
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve SHOP Property
    	/// </summary>
        [DataMember]
        public virtual string SHOP
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve AREA Property
    	/// </summary>
        [DataMember]
        public virtual string AREA
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve PRIORITY Property
    	/// </summary>
        [DataMember]
        public virtual string PRIORITY
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve PROBLEM_TYPE Property
    	/// </summary>
        [DataMember]
        public virtual string PROBLEM_TYPE
        {
            get;
            set;
        }

        #endregion

        public string TechAssignmentsToString
        {
            get
            {
                StringBuilder sb = new StringBuilder();
                int count = 0;
                foreach (TECHNICIAN_ASSIGNMENT assignment in TECHNICIAN_ASSIGNMENT)
                {
                    sb.Append(assignment.TECHNICIAN.NAME);
                    if (count < TECHNICIAN_ASSIGNMENT.Count - 1)
                    {
                        sb.Append(", ");

                    }
                    count++;
                }
                return sb.ToString();
            }
        }
        #region Navigation Properties
    
        [DataMember]
        public virtual ICollection<TECHNICIAN_ASSIGNMENT> TECHNICIAN_ASSIGNMENT
        {
            get
            {
                if (_tECHNICIAN_ASSIGNMENT == null)
                {
                    var newCollection = new FixupCollection<TECHNICIAN_ASSIGNMENT>();
                    newCollection.CollectionChanged += FixupTECHNICIAN_ASSIGNMENT;
                    _tECHNICIAN_ASSIGNMENT = newCollection;
                }
                return _tECHNICIAN_ASSIGNMENT;
            }
            set
            {
                if (!ReferenceEquals(_tECHNICIAN_ASSIGNMENT, value))
                {
                    var previousValue = _tECHNICIAN_ASSIGNMENT as FixupCollection<TECHNICIAN_ASSIGNMENT>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTECHNICIAN_ASSIGNMENT;
                    }
                    _tECHNICIAN_ASSIGNMENT = value;
                    var newValue = value as FixupCollection<TECHNICIAN_ASSIGNMENT>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTECHNICIAN_ASSIGNMENT;
                    }
                }
            }
        }
        private ICollection<TECHNICIAN_ASSIGNMENT> _tECHNICIAN_ASSIGNMENT;

        #endregion
        #region Association Fixup
    
        private void FixupTECHNICIAN_ASSIGNMENT(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (TECHNICIAN_ASSIGNMENT item in e.NewItems)
                {
                    item.ACTIVITY = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TECHNICIAN_ASSIGNMENT item in e.OldItems)
                {
                    if (ReferenceEquals(item.ACTIVITY, this))
                    {
                        item.ACTIVITY = null;
                    }
                }
            }
        }

        #endregion
    }
}
