

// -------------------------------------------------------------
// <copyright company="Pipeline Group, Inc." file="IRepository.cs">
// COPYRIGHT NOTICE

// SOFTWARE CONTAINING TRADE SECRETS

// Copyright 2012 Pipeline Group, Inc.  (PIPELINE GROUP, INC ). All rights reserved.

// This software and documentation constitute an unpublished work and contain valuable
// trade secrets and proprietary information belonging to the PIPELINE GROUP, INC .
// None of the foregoing material may be copied, duplicated or disclosed without the 
// express written permission of the PIPELINE GROUP, INC .

// PIPELINE GROUP, INC  EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES CONCERNING THIS 
// SOFTWARE AND DOCUMENTATION, INCLUDING ANY WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
// FOR ANY PARTICULAR PURPOSE, AND WARRANTIES OF PERFORMANCE, AND ANY WARRANTY THAT MIGHT 
// OTHERWISE ARISE FROM COURSE OF DEALING OR USAGE OF TRADE.
// NO WARRANTY IS EITHER EXPRESS OR IMPLIED WITH RESPECT TO THE USE OF THE SOFTWARE OR 
// DOCUMENTATION. 

// Under no circumstances shall PIPELINE GROUP, INC  be liable for incidental, special, indirect, direct 
// or consequential damages or loss of profits, interruption of business, or related expenses 
// which may arise from use of software or documentation, including but not limited to those 
// resulting from defects in software and/or documentation, or loss or inaccuracy of data 
// of any kind.

// </copyright>
// <author>$Author: pmontgomery $</author>
// <remarks>
//   $HeadURL: https://pipesvn.pipelinenetwork.com/svn/STP/Product/branches/Release/81/WebApp/Plugin_WorkAssignment/ModelAPI/IRepository.cs $
//   $LastChangedRevision: 8133 $ 
//   $LastChangedDate: 2013-07-26 09:56:05 -0700 (Fri, 26 Jul 2013) $ 
//   $LastChangedBy: pmontgomery $ 
// </remarks>  
// <summary>  
//   Represents a repository to data models  
// </summary> 
// ------------------------------------------------------------- 

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Data.Objects;

namespace Plugin_WorkAssignment.ModelAPI
{ 
	/// <summary>
	/// Interface representing an object repository
	/// </summary>
	public interface IRepository<T> 
	{
		/// <summary>
		/// Repository Unit Of Work Property
		/// </summary>
		IUnitOfWork UnitOfWork { get; set; }

		/// <summary>
		/// Retrieve all from the repository
		/// </summary>
		/// <returns>>A query</returns>
		IQueryable<T> All();

		/// <summary>
		/// Where clause for a query
		/// </summary>
		/// <param name="expression">Parameters for a where clause</param>
		/// <returns>A query</returns>
		IQueryable<T> Where(Expression<Func<T, bool>> expression);

		/// <summary>
		/// Add object to repository
		/// </summary>
		/// <param name="entity">Object to add to repository</param>
		void Add(T entity);

		/// <summary>
		/// Delete object from repository
		/// </summary>
		/// <param name="entity">Object to delete from repository</param>
		void Delete(T entity);

        /// <summary>
        /// Update repository object
        /// </summary>
        /// <param name="entity">Object to update</param>
        void Update(T entity);
	}
}

