// -------------------------------------------------------------
// <copyright company="Pipeline Group, Inc." file="IVW_TECHNICIAN_ASSIGN_AVAILRepository.cs">
// COPYRIGHT NOTICE

// SOFTWARE CONTAINING TRADE SECRETS

// Copyright 2012 Pipeline Group, Inc.  (PIPELINE GROUP, INC ). All rights reserved.

// This software and documentation constitute an unpublished work and contain valuable
// trade secrets and proprietary information belonging to the PIPELINE GROUP, INC .
// None of the foregoing material may be copied, duplicated or disclosed without the 
// express written permission of the PIPELINE GROUP, INC .

// PIPELINE GROUP, INC  EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES CONCERNING THIS 
// SOFTWARE AND DOCUMENTATION, INCLUDING ANY WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
// FOR ANY PARTICULAR PURPOSE, AND WARRANTIES OF PERFORMANCE, AND ANY WARRANTY THAT MIGHT 
// OTHERWISE ARISE FROM COURSE OF DEALING OR USAGE OF TRADE.
// NO WARRANTY IS EITHER EXPRESS OR IMPLIED WITH RESPECT TO THE USE OF THE SOFTWARE OR 
// DOCUMENTATION. 

// Under no circumstances shall PIPELINE GROUP, INC  be liable for incidental, special, indirect, direct 
// or consequential damages or loss of profits, interruption of business, or related expenses 
// which may arise from use of software or documentation, including but not limited to those 
// resulting from defects in software and/or documentation, or loss or inaccuracy of data 
// of any kind.

// </copyright>
// <author>$Author: pmontgomery $</author>
// <remarks>
//   $HeadURL: https://pipesvn.pipelinenetwork.com/svn/STP/Product/branches/Release/81/WebApp/Plugin_WorkAssignment/ModelAPI/IVW_TECHNICIAN_ASSIGN_AVAILRepository.cs $
//   $LastChangedRevision: 8168 $ 
//   $LastChangedDate: 2013-07-30 15:56:05 -0700 (Tue, 30 Jul 2013) $ 
//   $LastChangedBy: pmontgomery $ 
// </remarks>  
// <summary>  
//   Interface to available hours and assigned hours for all technicians for each day from a data source  
// </summary> 
// ------------------------------------------------------------- 

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
	
namespace Plugin_WorkAssignment.ModelAPI
{   
	/// <summary>
	/// Interface for VW_TECHNICIAN_ASSIGN_AVAIL Repository
	/// </summary>
	public interface IVW_TECHNICIAN_ASSIGN_AVAILRepository : IRepository<VW_TECHNICIAN_ASSIGN_AVAIL>
	{
        /// <summary>
        /// Get all available hours and assigned hours for all technicians in a shop for the specified work
        /// </summary>
        /// <param name="startWorkWeek">Start of work week to filter by</param>
        /// <param name="startWorkWeek">End of work week to filter by</param>
        /// <param name="shop">Shop technician's belong to</param>
        /// <returns>All available hours and assigned hours for all technicians in a shop for the specified work week</returns>
        /// <exception cref="DataBaseException">Database error getting data</exception>
        List<VW_TECHNICIAN_ASSIGN_AVAIL> GetAll(DateTime? startWorkWeek, DateTime? finishWorkWeek, string shop);
	}
}