// -------------------------------------------------------------
// <copyright company="Pipeline Group, Inc." file="Filename.cs">
// COPYRIGHT NOTICE

// SOFTWARE CONTAINING TRADE SECRETS

// Copyright 2012 Pipeline Group, Inc.  (PIPELINE GROUP, INC ). All rights reserved.

// This software and documentation constitute an unpublished work and contain valuable
// trade secrets and proprietary information belonging to the PIPELINE GROUP, INC .
// None of the foregoing material may be copied, duplicated or disclosed without the 
// express written permission of the PIPELINE GROUP, INC .

// PIPELINE GROUP, INC  EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES CONCERNING THIS 
// SOFTWARE AND DOCUMENTATION, INCLUDING ANY WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
// FOR ANY PARTICULAR PURPOSE, AND WARRANTIES OF PERFORMANCE, AND ANY WARRANTY THAT MIGHT 
// OTHERWISE ARISE FROM COURSE OF DEALING OR USAGE OF TRADE.
// NO WARRANTY IS EITHER EXPRESS OR IMPLIED WITH RESPECT TO THE USE OF THE SOFTWARE OR 
// DOCUMENTATION. 

// Under no circumstances shall PIPELINE GROUP, INC  be liable for incidental, special, indirect, direct 
// or consequential damages or loss of profits, interruption of business, or related expenses 
// which may arise from use of software or documentation, including but not limited to those 
// resulting from defects in software and/or documentation, or loss or inaccuracy of data 
// of any kind.

// </copyright>
// <author>$Author$</author>
// <remarks>
//   $HeadURL$
//   $LastChangedRevision$ 
//   $LastChangedDate$ 
//   $LastChangedBy$ 
// </remarks>  
// <summary>  
//     
// </summary> 
// ------------------------------------------------------------- 

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace Plugin_WorkAssignment.ModelAPI
{
    [DataContract]
    public partial class TECHNICIAN_AVAILABILITY
    {
        #region Primitive Properties
    
    	/// <summary>
    	/// Retrieve TECHNICIAN_ID Property
    	/// </summary>
        [DataMember]
        public virtual decimal TECHNICIAN_ID
        {
            get { return _tECHNICIAN_ID; }
            set
            {
                if (_tECHNICIAN_ID != value)
                {
                    if (TECHNICIAN != null && TECHNICIAN.ID != value)
                    {
                        TECHNICIAN = null;
                    }
                    _tECHNICIAN_ID = value;
                }
            }
        }
        private decimal _tECHNICIAN_ID;
    
    	/// <summary>
    	/// Retrieve WORK_DATE Property
    	/// </summary>
        [DataMember]
        public virtual System.DateTime WORK_DATE
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve AVAILABLE_HRS Property
    	/// </summary>
        [DataMember]
        public virtual decimal AVAILABLE_HRS
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual TECHNICIAN TECHNICIAN
        {
            get { return _tECHNICIAN; }
            set
            {
                if (!ReferenceEquals(_tECHNICIAN, value))
                {
                    var previousValue = _tECHNICIAN;
                    _tECHNICIAN = value;
                    FixupTECHNICIAN(previousValue);
                }
            }
        }
        private TECHNICIAN _tECHNICIAN;

        #endregion
        #region Association Fixup
    
        private void FixupTECHNICIAN(TECHNICIAN previousValue)
        {
            if (previousValue != null && previousValue.TECHNICIAN_AVAILABILITY.Contains(this))
            {
                previousValue.TECHNICIAN_AVAILABILITY.Remove(this);
            }
    
            if (TECHNICIAN != null)
            {
                if (!TECHNICIAN.TECHNICIAN_AVAILABILITY.Contains(this))
                {
                    TECHNICIAN.TECHNICIAN_AVAILABILITY.Add(this);
                }
                if (TECHNICIAN_ID != TECHNICIAN.ID)
                {
                    TECHNICIAN_ID = TECHNICIAN.ID;
                }
            }
        }

        #endregion
    }
}
