// -------------------------------------------------------------
// <copyright company="Pipeline Group, Inc." file="Filename.cs">
// COPYRIGHT NOTICE

// SOFTWARE CONTAINING TRADE SECRETS

// Copyright 2012 Pipeline Group, Inc.  (PIPELINE GROUP, INC ). All rights reserved.

// This software and documentation constitute an unpublished work and contain valuable
// trade secrets and proprietary information belonging to the PIPELINE GROUP, INC .
// None of the foregoing material may be copied, duplicated or disclosed without the 
// express written permission of the PIPELINE GROUP, INC .

// PIPELINE GROUP, INC  EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES CONCERNING THIS 
// SOFTWARE AND DOCUMENTATION, INCLUDING ANY WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
// FOR ANY PARTICULAR PURPOSE, AND WARRANTIES OF PERFORMANCE, AND ANY WARRANTY THAT MIGHT 
// OTHERWISE ARISE FROM COURSE OF DEALING OR USAGE OF TRADE.
// NO WARRANTY IS EITHER EXPRESS OR IMPLIED WITH RESPECT TO THE USE OF THE SOFTWARE OR 
// DOCUMENTATION. 

// Under no circumstances shall PIPELINE GROUP, INC  be liable for incidental, special, indirect, direct 
// or consequential damages or loss of profits, interruption of business, or related expenses 
// which may arise from use of software or documentation, including but not limited to those 
// resulting from defects in software and/or documentation, or loss or inaccuracy of data 
// of any kind.

// </copyright>
// <author>$Author$</author>
// <remarks>
//   $HeadURL$
//   $LastChangedRevision$ 
//   $LastChangedDate$ 
//   $LastChangedBy$ 
// </remarks>  
// <summary>  
//     
// </summary> 
// ------------------------------------------------------------- 

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace Plugin_WorkAssignment.ModelAPI
{
    [DataContract]
    public partial class VW_TECHNICIAN_UTILIZATION
    {
        #region Primitive Properties
    
    	/// <summary>
    	/// Retrieve TECH_NAME Property
    	/// </summary>
        [DataMember]
        public virtual string TECH_NAME
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve SHOP Property
    	/// </summary>
        [DataMember]
        public virtual string SHOP
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve AVAILABLE_HRS Property
    	/// </summary>
        [DataMember]
        public virtual decimal AVAILABLE_HRS
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve WORK_DATE Property
    	/// </summary>
        [DataMember]
        public virtual System.DateTime WORK_DATE
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve SCHEDULED_HRS Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> SCHEDULED_HRS
        {
            get;
            set;
        }
    
    	/// <summary>
    	/// Retrieve UTILIZATION_PCT Property
    	/// </summary>
        [DataMember]
        public virtual Nullable<decimal> UTILIZATION_PCT
        {
            get;
            set;
        }

        #endregion
    }
}
